# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x] # Specify the Node.js version
    defaults:
      run:
        working-directory: /home/ubuntu/actions-runner/_work/crmmasterBACKEND/crmmasterBACKEND

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up the Node.js environment
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Step 3: Cache npm modules
      - name: Cache Node.js Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 4: Upgrade npm to the latest version
      - name: Upgrade npm
        run: npm install -g npm@latest

      # Step 5: Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 6: Set up environment variables
      - name: Set Up Environment Variables
        run: echo "${{ secrets.PROD }}" > .env

      # Step 7: Start or restart PM2 process
      - name: Start or Restart PM2 Process
        run: |
          if pm2 list | grep -q "Backend"; then
            echo "Stopping existing process..."
            pm2 stop Backend
            pm2 delete Backend
          fi
          echo "Starting new process..."
          pm2 start ecosystem.config.js
          pm2 save

      # Step 8: Debug PM2 processes
      - name: Debug PM2 Processes
        run: pm2 list

